all:
  hosts:
    # 192.168.1.57:
    192.168.1.77:
    192.168.1.67:
    192.168.1.87:
  children:
    workers:
      hosts:
        192.168.1.87:
        192.168.1.67:
    masters:
      hosts:
        192.168.1.77
    # load_balancers:
    #   hosts: 
    #     192.168.50.117:
    # management:
    #   hosts:
    #     192.168.1.67: