apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-pvc
  namespace: plex
  labels:
    app: media
spec:
  storageClassName: nfs-storage-media
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Gi