apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: nfs-storage-nextcloud
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 95Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-shared-pvc
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: nfs-storage-k8sdata
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi