---
# tasks file for fan_control
- name: Ensure required packages are installed
  ansible.builtin.package:
    name: python3-rpi.gpio
    state: present

- name: Deploy fan control script
  ansible.builtin.template:
    src: fan_control.py.j2
    dest: /usr/local/bin/fan_control.py
    mode: '0755'

- name: Deploy systemd service for fan control
  ansible.builtin.template:
    src: fan_control.service.j2
    dest: /etc/systemd/system/fan_control.service

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start fan control service
  ansible.builtin.systemd:
    name: fan_control
    enabled: true
    state: started
