kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner-k8sdata
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-k8sdata
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: dynamic-nfs-k8sdata
            - name: NFS_SERVER
              value: 192.168.1.77
            - name: NFS_PATH
              value: /media/480_ssd/k8sdata
        - name: nfs-client-provisioner-nextcloud
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-nextcloud
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: dynamic-nfs-nextcloud
            - name: NFS_SERVER
              value: 192.168.1.77
            - name: NFS_PATH
              value: /media/480_ssd/nextcloud
        - name: nfs-client-provisioner-media
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-media
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: dynamic-nfs-media
            - name: NFS_SERVER
              value: 192.168.1.77
            - name: NFS_PATH
              value: /media/480_ssd/media
      volumes:
        - name: nfs-k8sdata
          nfs:
            server: 192.168.1.77
            path: /media/480_ssd/k8sdata
        - name: nfs-nextcloud
          nfs:
            server: 192.168.1.77
            path: /media/480_ssd/nextcloud
        - name: nfs-media
          nfs:
            server: 192.168.1.77
            path: /media/480_ssd/media