apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage-k8sdata
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: dynamic-nfs-k8sdata
parameters:
  archiveOnDelete: "false"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage-nextcloud
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: dynamic-nfs-nextcloud
parameters:
  archiveOnDelete: "false"