apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-pvc
  namespace: resume-app
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi