apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-pvc
  namespace: resume-app
spec:
  storageClassName: nfs-storage-k8sdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi