apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: net-test
spec:
  dnsNames:
    - nginx.test
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer