apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: net-test
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: cgrpi.ml
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: nginx
            port: 
              number: 80